<?php
/**
 * @var $block \Adfix\Squarefeed\Block\Adminhtml\Main
 */
?>

<script type="text/javascript">
    function iframeLoad() {
        var iframeElement = document.getElementById('SquarefeedIframe');
        iframeElement.contentWindow.postMessage({
            'command': "setPlatforms",
            'platforms': <?= /* @escapeNotVerified */ $block->getPlatformData()?>
        }, '*');
        
        iframeElement.contentWindow.postMessage(<?= /* @escapeNotVerified */ $block->getUserData() ?>, '*');

        var eventMethod = window.addEventListener ? 'addEventListener' : 'attachEvent';
        var eventer = window[eventMethod];
        var messageEvent = eventMethod == 'attachEvent' ? 'onmessage' : 'message';
        eventer(messageEvent, function (e) {
            if (e.data.command === 'resize') {
                document.getElementById('SquarefeedIframe').style.height = e.data.height + 'px';
            }

            if (e.data.command === 'reload') {
                window.location.reload();
            }
        }, false);
    }
</script>

<iframe src="<?= $block->escapeHtml($block->getIframeUrl()) ?>"
        id='SquarefeedIframe'
        scrolling='yes'
        frameBorder='0'
        allowfullscreen
        align='center'
        onload='iframeLoad()'
        style='width: 100%; min-height: 500px'>
    <p><?php __('Your browser does not support iFrames.'); ?></p>
</iframe>